Skip to content
Navigation Menu
ducnn230288
/
laravel-react

Type / to search
Code
Issues
Pull requests
Actions
Projects
Security
Insights
Checks
refactor(base): reorganize angular #386
Jobs
Run details
Workflow file for this run
.github/workflows/checks.yml at 0006746
---
name: Checks

on:
  push:
    branches: ['master']
  pull_request:
    branches:
      - 'master'
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run actions/checkout@v2
        uses: actions/checkout@v2
      - name: Build the docker compose stack
        run: docker compose -f .docker/docker-test.yml up -d
      - name: Wait for build docker
        if: ${{ !cancelled() }}
        run: sleep 2.3
      - name: Run Test Backend
        run: docker compose -f .docker/docker-test.yml exec -T server ./vendor/bin/phpunit
      - name: Run Clear config
        if: ${{ !cancelled() }}
        run: docker compose -f .docker/docker-test.yml exec -T server php artisan config:clear
      - name: Generate key
        if: ${{ !cancelled() }}
        run: docker compose -f .docker/docker-test.yml exec -T server php artisan key:generate
      - name: Run Migration && Seed Database
        if: ${{ !cancelled() }}
        run: docker compose -f .docker/docker-test.yml exec -T server php artisan migrate:refresh --seed
      - name: Run Test Frontend
        if: ${{ !cancelled() }}
        run: docker compose -f .docker/docker-test.yml exec -T server robot -d .e2e/result .e2e/integration/*.robot
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: output
          path: output/
          retention-days: 30
#       docker compose -f .docker/docker-build.yml up -d --build
#       docker compose -f .docker/docker-build.yml run --rm server sh -c "npm run migration && npm run seed"
refactor(base): reorganize angular · ducnn230288/laravel-react@0006746
